---
# tasks file for launch_rhel_ami
- name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: Get the SG ID for {{ ec2_name_prefix }}-sg
  ec2_group_info:
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
      group-name: "{{ ec2_name_prefix }}-sg"
    region: "{{ ec2_region }}"
  register: sg_net_facts

- name: Get the subnet IDs for {{ ec2_name_prefix }}-vpc
  ec2_vpc_subnet_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc_net_facts.vpcs[0].id }}"
  register: subnet_info

- name: Get subnet ids
  set_fact:
    subnet_ids: "{{ subnet_info
      | selectattr('subnet.id', 'defined')
      | map(attribute='subnet.id')
      | list
      | unique }}"

- name: "Find current, region-specific Windows AMI."
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ami_name }}"
  register: found_amis

- name: "Set AMI value"
  set_fact:
    rhel_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  when: found_amis.images is defined

- name: "Start RHEL instances."
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    region: "{{ ec2_region }}"
    image: "{{ rhel_ami.image_id }}"
    instance_type: "{{ instance_type }}"
    group_id: "{{ sg_net_facts.security_groups[0].group_id }}"
    vpc_subnet_id: "{{ item }}"
    wait: yes
    wait_timeout: 500
    exact_count: "{{ instance_count }}"
    count_tag:
      count_tag: Name
    instance_tags:
      Name: "{{ instance_tag_inventory }} Windows Server"
      Inventory: "{{ instance_tag_inventory }}"
    user_data: "{{ lookup('template', '{{ role_path }}/templates/userdata.txt.j2') }}"
  loop: "{{ subnet_ids }}"
  register: ec2_result

- debug:
    msg: "{{ ec2_result }}"

- name: "Wait for connection on all hosts."
  wait_for_connection:
    host: "{{ item.public_ip }}"
    timeout: 300
  loop: "{{ ec2_result.instances }}"

- name: Show public IP
  debug:
    msg: "Public IP: {{ item.public_ip }}"
  loop: "{{ ec2_result.instances }}"

