---
# tasks file for launch_rhel_ami
- name: Get the VPC ID for {{ ec2_name_prefix }}-vpc
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ ec2_name_prefix }}-vpc"
    region: "{{ ec2_region }}"
  register: vpc_net_facts

- name: Set the VPC ID
  set_fact:
    vpc_id: "{{ vpc_id }}"

- name: Get the SG ID for {{ ec2_name_prefix }}-sg
  ec2_group_info:
    filters:
      vpc-id: "{{ vpc_id }}"
      group-name: "{{ ec2_name_prefix }}-sg"
    region: "{{ ec2_region }}"
  register: sg_net_facts

- name: Get the subnet IDs for {{ ec2_name_prefix }}-vpc
  ec2_vpc_subnet_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
  register: subnet_info

- name: "Find current, region-specific AMI."
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ami_name }}"
  register: found_amis

- name: "Set AMI value"
  set_fact:
    rhel_ami: "{{ found_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}"
  when: found_amis.images is defined

- name: "Start RHEL instances."
  ec2:
    key_name: "{{ ec2_name_prefix }}-key"
    region: "{{ ec2_region }}"
    image: "{{ rhel_ami.image_id }}"
    instance_type: "{{ instance_type }}"
    group_id: "{{ sg_net_facts.security_groups[0].group_id }}"
    vpc_subnet_id: "{{ subnet_info.subnets[0].id }}"
    wait: yes
    wait_timeout: 500
    exact_count: 1
    count_tag:
      Name: "{{ instance_tag_inventory }} RHEL server {{ item }}"
    instance_tags:
      Role: rhel_server
      Platform: RHEL
      Name: "{{ instance_tag_inventory }} RHEL server {{ item }}"
      Inventory: "{{ instance_tag_inventory }}"
      Stage: "instantiated"
  loop: "{{ range(1, instance_count +1)|list }}"
  loop_control:
    label: "{{ item }}"
  register: ec2

- name: "Wait for connection on all hosts."
  wait_for:
    host: "{{ item['tagged_instances'][0]['private_ip'] }}"
    port: 22
    timeout: 500
  loop: "{{ ec2.results }}"
  loop_control:
    label: "{{ item['tagged_instances'][0]['private_ip'] }}"

